apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-nodes
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: ElementalPassword
        - name: brynn
          passwd: SUSEPassword
          ssh_authorized_keys:
            - >-
              ssh-ed25519
              AAAAC3NzaC1lZDI1NTE5AAAAIM6dlqga9TQk0Y/MlWmabyteU1Q1cy4i+d+zNuX9WACs
              brynn@lenovo
    elemental:
      install:
        reboot: true
        debug: true
      install:
        device-selector:
          - key: Name
            operator: In
            values:
              - /dev/sda
              - /dev/vda
              - /dev/nvme0
          - key: Size
            operator: Gt
            values:
              - 25Gi
        snapshotter:
          type: btrfs
      registration:
        auth: tpm
        emulate-tpm: true
        emulated-tpm-seed: -1
      reset:
        reboot: true
        reset-oem: true
        reset-persistent: true
  machineInventoryLabels:
    element: fire
    manufacturer: "${Product/Vendor}"
    productName: "${Product/Name}"
    serialNumber: "${Product/Serial Number}"
    machineUUID: "${Product/UUID}"
    CPUModel: ${System Data/CPU/Model}
    CPUVendor: ${System Data/CPU/Vendor}
    CPUVendorTotalCPUCores: ${System Data/CPU/Total Cores}
    NumberBlockDevices: ${System Data/Block Devices/Number Devices}
    NumberNetInterface: ${System Data/Network/Number Interfaces}
    TotalCPUThread: ${System Data/CPU/Total Threads}
    TotalMemory: ${System Data/Memory/Total Physical Bytes}
    hypervisor: VMware
    machineUUID1: ${System Information/UUID}
    manufacturer1: ${System Information/Manufacturer}
    productName1: ${System Information/Product Name}
    serialNumber1: ${System Information/Serial Number}
