apiVersion: v1
kind: Config
clusters:
- name: "rmc"
  cluster:
    server: "https://rancher.harrison.local/k8s/clusters/local"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVHekNDQ\
      XdPZ0F3SUJBZ0lVSW9GT2lVdUJFU3JFUXAxMTB0dllVLytoL3lNd0RRWUpLb1pJaHZjTkFRRUwKQ\
      lFBd2dad3hDekFKQmdOVkJBWVRBbFZMTVE4d0RRWURWUVFJREFaRWRYSm9ZVzB4R1RBWEJnTlZCQ\
      WNNRUZOMApiMk5yZEc5dUxXOXVMVlJsWlhNeEVUQVBCZ05WQkFvTUNFaGhjbkpwYzI5dU1Rd3dDZ\
      1lEVlFRTERBTkVZV1F4CkZ6QVZCZ05WQkFNTURrSnllVzV1SUVoaGNuSnBjMjl1TVNjd0pRWUpLb\
      1pJaHZjTkFRa0JGaGhpY25sdWJpNW8KWVhKeWFYTnZia0JuYldGcGJDNWpiMjB3SGhjTk1qUXdNa\
      kEwTVRZek9UQXdXaGNOTWprd01qQXlNVFl6T1RBdwpXakNCbkRFTE1Ba0dBMVVFQmhNQ1ZVc3hEe\
      kFOQmdOVkJBZ01Ca1IxY21oaGJURVpNQmNHQTFVRUJ3d1FVM1J2ClkydDBiMjR0YjI0dFZHVmxje\
      kVSTUE4R0ExVUVDZ3dJU0dGeWNtbHpiMjR4RERBS0JnTlZCQXNNQTBSaFpERVgKTUJVR0ExVUVBd\
      3dPUW5KNWJtNGdTR0Z5Y21semIyNHhKekFsQmdrcWhraUc5dzBCQ1FFV0dHSnllVzV1TG1oaApjb\
      kpwYzI5dVFHZHRZV2xzTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb\
      0NnZ0VCCkFLWlRsS1c3WHlxY1BtcFRKelBxSCtPRUVVcHlwRTQwMEpEdy9tMFFGR0hud0pCZlpON\
      TNqQ0JyOEt1T0dQeVEKUFo4MURpVktGNGdpT3F5bWNCSmt5VmFtb2lOU0Iyc1FSZ05iek16U3dza\
      jB2SHNoMUVnUVZQU1lzYitKOE5obQp1RHFQcU1jRld5REo5MEt2Tld5RGxwd2xMcldSNlYzTUM0K\
      zNDbWZEVXhJUE9XSm5VbVZsVXd4VjJubG1CY0ZxCklla1hXZzZPUUhHTEQ2ZTJxdXlJREhFSmhEe\
      GUzRWpaV2ZGOXhweEU0b2FZOStOYWp4TFdCc1lzMUFVd2tabXgKekx0YzE0L3ZyZXNCcVdEamlNN\
      mhRcGZiNGFZaVQ2eUpLTzdqSjZvcDhpYXduR3Y0N1hMdS9BV0lKd3g4NWE1WQpjanlqRVhOcC9KV\
      XZxUHFzdjM1eWlaOENBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGQVhoNEZnWWVIajZIWXRNCitTO\
      UNCNEhJVEI0dE1COEdBMVVkSXdRWU1CYUFGQVhoNEZnWWVIajZIWXRNK1M5Q0I0SElUQjR0TUE4R\
      0ExVWQKRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBZEUzUXg3S2xOU\
      UZWekxjOURmeEIwWgo3aGRCV0JlMlR5WmlNWEN0UlJTTmhBTG9TbkpFL05qQ1IrT3FWeWVVTUE2e\
      HUreEZEWnZDanVYT1pqaFF3czJHCkQzY1lFdkZrUk9hd0RZUXBYRHN4a0FVeXNkTWJXbGxlOFZXT\
      mxXUVNHK0s3S1hxM1Bkd1M1NTZDbHNDNUp2dkgKVGRhMDdDblczUnErMGxuMTBma2pzVkZPWVBNV\
      VdQcHZQK0FqeXBzUmhneTEyN2FXNmIzdkgyb1o0S0lpdjl3LwoydDFSbWIyTEFTVm5HSUlISzlzL\
      0N4QXBqbGxJbTJyNGd3Zzg0SmRFV3I0aDFTdnN5M0ZMblJrak9nUWM5QWJKCi9odG9VSXVmUWQzc\
      DdWUVVkbzRrR3FaT0VScTg2MTlkdjhmOFpRYXV2QUQ2MW5FS29GK1lVTUFpUGZQc2tldz0KLS0tL\
      S1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="

users:
- name: "rmc"
  user:
    token: "kubeconfig-user-fg976sbww5:d9jccpjfljplpmg5bl4vdfl58h9cqhf9q7wd9fpchrg6b8vhg7z4wq"


contexts:
- name: "rmc"
  context:
    user: "rmc"
    cluster: "rmc"

current-context: "rmc"
